### ISSUE TITLE
Where did the stickers go to?

### ISSUE THREAD

**Issue by herrkessler** [crystal-lang/crystal-website#60] opened 2018-02-13 14:59 UTC
Github is probably **NOT** the perfect place to ask this, but does anyone have a clue where to get the Crystal Stickers, as this link isn't working anymore?

[https://www.stickermule.com/user/1070777225/stickers](https://www.stickermule.com/user/1070777225/stickers)

**Comment by straight-shoota** [comment] 2018-02-13 15:56
But it is the perfect place to initiate that this link get's fixed on the crystal website (https://crystal-lang.org/media/).

**Comment by matiasgarciaisaia** [comment] 2018-02-14 12:31
Hey, thanks for reporting! This _is_ the right place to ask, since it's kind of a website bug :)

Just contacted StickerMule on the subject. I think I recall something about them discontinuing that service, but I'm not sure - so we'll wait for their answer 👍

**Comment by matiasgarciaisaia** [comment] 2018-02-14 12:42
OK - StickerMule confirmed they've closed their marketplace (the service we were using), so we need to look for an alternative service.

If anyone wants to recommend some service you've tried, you're more than welcome!

I'll probably just remove the message on the site for now.

**Comment by bew** [comment] 2018-02-14 17:37
I've used Unixstickers in the past for my stickers: https://www.unixstickers.com

It works very well, and they can make other furnitures too (mug, T-shirt, ...)

**Comment by sdogruyol** [comment] 2018-02-14 17:43
There's also https://www.redbubble.com :+1:

**Comment by straight-shoota** [comment] 2018-02-14 17:48
Yeah, but they decide what stickers they print. They don't just sell any stickers for you.
However, unixstickers has a [trello board for suggestions](https://trello.com/b/WcWf6kdF). Though there are already a few other projects on the list.

**Comment by bew** [comment] 2018-02-14 18:35
yeah @straight-shoota, this trello is for requesting stickers, but on the home page there is a contact email for organization to send them new logos: `info@unixstickers.com`
> Interested in having unixstickers produce stickers & co with your logo? Drop us a line.

**Comment by herrkessler** [comment] 2018-02-15 08:40
How about [http://devstickers.com/](http://devstickers.com/)? 

Question is if that's "just" a link list, as in the end all the links go to reddbubble.

**Comment by herrkessler** [comment] 2018-02-28 08:41
and... any news on this topic?

**Comment by sdogruyol** [comment] 2018-03-06 16:55
Yup, stickker is a great service :+1: It's actually from @f which is also a Kemal contributor :smile:

**Comment by straight-shoota** [comment] 2022-01-11 13:37
Closing. This is not an actionable item.

**Closed by straight-shoota** 2022-01-11 13:37 UTC
